kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  serviceAccountName: pipeline
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: image-registry.openshift-image-registry.svc:5000/cicd/spring-web-quickstart:dsdsds
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP