apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: custom-approval
spec:
  params:
  - name: recipients
    type: string
    description: recipient email addresses
  - name: pipeline_name
    type: string
  - name: pipelinerun_name
    type: string  
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - image: docker.io/paichayon1/tekton-approve:0.4
    name: wait-approve
    script: |
      # loop until approval=true
      echo $(params.recipients)
      echo $(params.pipeline_name)
      echo $(params.pipelinerun_name)
      code=$(shuf -i 1000000000000000-9999999999999999 -n 1)
      cicd_ns="cicd"
      basedomain="$cicd_ns.apps.524vf.dynamic.opentlc.com"
      echo "code number: $code" 
      approve_link="<b>Pipeline name:</b> $(params.pipeline_name) <br> <b>Pipeline Approve Code:</b> $code<p>Click link below to Approve:<br>http://$(params.pipelinerun_name)-wait-for-approve-pod-$basedomain"
      python sendgmail.py "$user" "$password" "$(params.recipients)" "PipelineSystem - Approve Code for $(params.pipeline_name)" "$approve_link" 
      python approval.py "$code"



