apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-approve
  namespace: cicd
spec:
  tasks:
# Task Before wait to approve
    - name: first-step
      params:
        - name: cmd
          value: echo "First"
      taskRef:
        kind: ClusterTask
        name: bash
      workspaces:
        - name: source
          workspace: source
# Prepare service and route to approve URL          
    - name: custom-approval-pre-oc
      params:
        - name: pipelinerun_name
          value: $(context.pipelineRun.name)     
      runAfter:
        - first-step
      taskRef:
        kind: Task
        name: custom-approval-pre-oc
# Waiting Task for approve
    - name: wait-for-approve
      params:
        - name: image_tag
          value: "0.0.0"
        - name: environment
          value: "default"
        - name: recipients
          value: ptanvann@redhat.com
        - name: pipeline_name
          value: $(context.pipeline.name) 
        - name: pipelinerun_name
          value: $(context.pipelineRun.name)     
      runAfter:
        - first-step
      taskRef:
        kind: Task
        name: custom-approval
# Clean Service and Route
    - name: custom-approval-post-oc
      params:
        - name: pipelinerun_name
          value: $(context.pipelineRun.name)     
      runAfter:
        - wait-for-approve
        - custom-approval-pre-oc
      taskRef:
        kind: Task
        name: custom-approval-post-oc
# Task after aprove
    - name: after-approve
      params:
        - name: cmd
          value: echo $(tasks.wait-for-approve.results.approve_result)
      runAfter:
        - custom-approval-post-oc
      taskRef:
        kind: ClusterTask
        name: bash
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source