apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: custom-approval
spec:
  steps:
  - image: docker.io/paichayon1/tekton-approve:0.3
    name: wait-approve
    script: |
      # loop until approval=true
      echo "$(context.pipelineRun.name)"
      code=$(shuf -i 1000000000000000-9999999999999999 -n 1)
      echo "code number: $code" 
      python approval.py "$code"



