apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: custom-approval-post-oc
spec:
  params:
  - name: approve_result
    type: string 
  - name: pipelinerun_name
    type: string  
  steps:
  - env:
      - name: HOME
        value: /tekton/home
    image: >-
      image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    name: oc
    resources: {}
    script: |
      #!/usr/bin/env bash
      svc_remove="$(params.pipelinerun_name)-wait-for-approve-pod"
      echo $svc_remove
      oc delete service $svc_remove
      oc delete route $svc_remove
      echo "$(params.approve_result)"
      if [[ $(params.approve_result) == reject ]]; then
          exit 1
      fi 

    securityContext:
      runAsNonRoot: true
      runAsUser: 65532