apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug-git-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "debug-git-task"
spec:
  description: >-
    debug-task
  workspaces:
    - name: source
  steps:
    - name: debug-git-task
      image: cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
      workingDir: "$(workspaces.source.path)"
      command: ["sleep", "infinity"]
