apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug-git-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "debug-git-task"
spec:
  params:
  - name: git-repo-url
    type: string
    default: ""
  - name: git-revision
    type: string
    default: ""
  - name: git-repo-name
    type: string
    default: ""
  - name: ext-branch
    type: string
    default: ""
  - name: environment
    type: string
    default: ""
  description: >-
    debug-git-task
  workspaces:
    - name: app-source
  steps:
    - env:
        - name: git-repo-url
          value: $(params.git-repo-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: git-repo-name
          value: $(params.git-repo-name)
        - name: ext-branch
          value: $(params.ext-branch)
        - name: environment
          value: $(params.environment)          
    - name: debug-git-task
      image: cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
      workingDir: "$(workspaces.app-source.path)"
      command: ["sleep", "infinity"]
