apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: debug-ubi7-task
  labels:
    app.kubernetes.io/version: "7"
  annotations:
    tekton.dev/pipelines.minVersion: "7"
    tekton.dev/displayName: "debug-ubi7-task"
spec:
  description: >-
    debug-task
  workspaces:
    - name: app-source
  steps:
    - name: debug-task
      image: registry.redhat.io/ubi7/ubi-minimal
      workingDir: "$(workspaces.app-source.path)"
      command: ["sleep", "infinity"]
