apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-pat-secret
  namespace: cicd
spec:
  encryptedData:
    GIT_CREDS_PSW: AgAyk2ECiZiT0ao5mWf7n2W7i7H+A4CrvC4/rw/YWwj6f42kJeg5kScjIa8Ce5wbn/mUeU8zwuWR4qzmL/xVua63cV3D9Aq1vTa2F/+mQOb4oypU67WcbY0svfSErNNYIXtOdWuP7yhn6XrwCR40FbYpNYDYosery232Y0Rc9cyv6c5NemsMK4FcUmGhiVKNJqZ27Eun/KusIAavrTlPtPPuMRH/EtwjdHpC/qvNAqVZ0xl9YsscHJ7STZ4ViiwnmYLL5oJSgttVpq/eOrFKYyaIDS050ESeoU3IITl40IQRbb8lx/GEnk7ShkvBdAaXh1XtAuxDDv0hZrznOTQJ/OZ+4kmwoTTfiugIfFEyHR40Q02lz+gmLk95cV7VmcABA/WPkMZlw4c/5s/mT/9ESTI9fFE+GfivsXAHLiySF4zorVmT0kouyWHOCVnCzTDge1pitY2CdRterL2DjabG2liKk2lGrucxbaWzINymTAYC/LsN5AgnnPho/GDo2GIRxRX1CeWF7qretZ9C8PYpfA+0azyT70OXxESwOrrhGR8hM1H32Kb5I8RFZ0pF68cwCpdfocF/fWb/a0lqf4QvNqioVBpgbxERuEJMhbnisrY64HblDFlWpCCu4ut3/DLCn7eKn41o4eziKWLfHySf3nYFjgkt0Uq0nZ8NI7ZSSunRzbFy2zj4aA5ajABKDjWazTMpHPhwVScEJWGDqqNpQe7k9/oY74s8khgMWdG7VJubWh1KOumUsj+u
    GIT_CREDS_USR: AgBs92CMDlg11mGvD5wRqzstujKKYqqyj6peJBS3VdjA/EQOi0KAIehcnV5lpWeAdWRBNdBuFMwNiPPkyLinMtq3Z4OWe7TwiyRZB1ibGuisVeDX/NoTXrKk7wOPoJBuMPVkh+jTkC9AZR9S4nidN4iAJzNIn5SRwgqiByLaqG/sgJrh0gcERSSDYJ4/p97Dmk9IdtNX+D/tHcZfmOcyWPaIEswQaR1w3lGANwLBklJ6ZLznHfr+Y8IX9lfG+OXEvnfG9ZETPn8+m4AI0zuLA5hzoE0GMYStifbWxr+TWm2Y6zPkT+4rmTIlWf5C5ge+h0UIpqzpIUc3vrTyhpLegHw/yF9Y4o/XD1vBogYQH26DUcczV6VxuqwM/QpKHP0zB8B1zDxtKsBrOCyzyitLCAJVaSoHnCgK8uwBwto4KKa9bFMjl794OJVOtAF5jfTuL/W/pVlJtxSemKvIVXmIaEfmCHpnbyr1F1Gr1+HsO6/KmhuwSoWGeGsU8KlJcAEcyzCSxGbYK6/bGHeV3fm001OG76clf1joPRr43Br2ZEM1Za+qnhR4+AD6D2jSdqCG/Ggb5pSkGTUwx9Owz7XugW78uX/X+5noLYqUsTeUiXooeQsyC+5bmSyOKj2+wEblSAcavMCdhyiYE8x9fXio57vC7oNBHk4WBfjFnwi50F62p9y5BUxd/l60i/jcM0NM7SWsnOB3+swCdrZCVK0=
  template:
    metadata:
      creationTimestamp: null
      name: github-pat-secret
      namespace: cicd
