apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-pat-secret
  namespace: cicd
spec:
  encryptedData:
    token: AgB9lOP38ugFvW7tjZAZSF0tYlfcYQYkQH4ArGranVOF1Nfi5WnMBBLBxpn1jMIo4ukXrPkpQUBS8NFeMG3HI7x0M5voVf7hPW594dbDDfP/PoFQ/H+no3h+D+dpEiHucnjinUbYjLDmrUPmTlzSqz6ATHkdZ0IxKcuMT6m3Zd104HdAwO1CJWm/bHyOLhqzW0SqyDIrcMqV+oRl/SpWvzNTdDfHJo2ASALqv0Dd8yJBe6/rVg8CeiENYwTxQeqHatSYhLRZL6St5CHficnI5xRrlZIeHtKXEJZkKbKAJk03Iqzj40MDfWxXiKmirWXXOWzYnYEMEphq+XYMwdOnpqiq9p3vRLe65va4IIDdPwZXzerD91javNrayanIzyZsus4BulOHYzRNd0TCmHViJVuoM6ZK7SFuoVegA9nX1UB3Yq13ckQ0/fRW29GUl4Tfc37oeeBvtjuKd8Pq0Elvo48FIbEAyQxAQuNnXODDDpgA2ra9mP1+/Y9t5rtL1V9u2mKc2NbewQPPym+cbmG1XzBgh22i8dXtfL1wtPrLkMAeeKxwh5Ta7+4uAt68c2L8mZE8XdMZJ81quNBDvwowROkG1zQYIv6DfK87NPoKMUbwhprbMAcY72HpCdHDrTtvtSl6OdX/luFOwHQiQY1yPmyOscNLl6vSWNCxXvdC6L+cDDNotmV/IkG3T5DkvFohw0Uz1U6ZPLJTSmk8FYeAjl1u+6CXlTpW2h3bo4Y1zvQma2ckTVJKuGXk
    user: AgCUFWlgQDxukbGYWd/o+lCEqyZz/PFcft0S+R3XnxhUPSoAH5ZoMuXFLSGHRJ1SfRgbOiG/484P4rhqryaa+1Sfx1C2bbNZLE5YrkQNzvY2OjMNnNArxRrRogVFY8g6MSCkfRovCWyyFvD9SmLaXFt+3O9k3AxmwvpRsbiSmJVr/L0OwlzoGyCUeoI0tsoWDjPB1Jx3EEDnMuReZtuu3D52/l6yBHg4MrjVuiOjIYuoqIQOAIVJdlf/6BKoMdimCh/rlOAfpKTC+hUbk43K2I/Fdce4YcrHdiHQfSAILvT3Ivuogs3sQ5T9V4iEYZl1zDxglp4tPtL5wVEGp+t6XueRYQp3Wvoc9HKVebge/6ZNCeoLQAurgQxXHlzD8e1smj8/Yjm5Loz5AKZmlVzlK0/lhthKgXcMCnQxpQAL1KN/Wk8nJEKY4ta0s2OUJiTjmwmVdyosr0Vuj4L8bkn9TqM/xHXoPvL3VdeVoFHFSM0u0M1RO+tFvJDO1YlXgTYxHgLbO+DQqWoCA9cM75WQJXnLA9Q0UfZeB2leoGf2XxwOqzl1t4Ak3zR4/FpiB2l3t3gxYWGC8iqYR4oRw+1tqR+3jjgDjMMs7suyksy8Nh08MhH0ojxim51UnkyOzI9h/Hj7+6d3eiYdncBvQC75FEM9qkmNfJ4f7is5HBvYFIcFTd353iHAsHSwraTyUhJkxNIlWiIWdnhbu08ypuI=
  template:
    metadata:
      creationTimestamp: null
      name: github-pat-secret
      namespace: cicd
    type: Opaque
