apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    secretToken: AgCS9PuVfuRf4vjZYhcrb3gZY1IQ8XHeuHtEqGJhMC+dUd1QYp2aBAqRpDORJH8PMW5vn7IOABwVuGZMAM872t4wwWuHdA7U8Ka8wKWEQxRnIA5yIHGHf+9XVav6ymGuiwTQ1jtkpvOKzUNERmdpOkpQ02gldAhyj289WS7wS6DQ2r+YJUPL702Et9MqQsqJVq7UsZLwOTXb3ZONXXVGTjB65BpL5Szhg4cONMnKVv28BRP36EnVAkrtTFPkQsO5+/5R5jbOu7BGLo0guFTSLS3oqdPlMKC0iMuu45mi57GKLrkvL0Y6cjPM7Omjn2qzI3JHYPVaHleSxToPsQT2L0UFtpxhSr3S+m7cOw6x1p1lkLJKmg+OT3kTbNn9gI86X71RSW/1q6m3EQBwb1ecKsRc3pqocTlCyVYIMYzCmejiGs4mPQ3OPx0ea0Plt/jbI8xhTOrqKS2xqiu4OL7jEUhWE/QBOY8s+IzmkLukR2Up9BjmZKNL8GZsNI21QJb1ABqYT4truTrUjTUrC5czVziVh8Wh+zzF1qmgrHLwlea7tWMI7oDXgU22iiu2g+9PYaHJwmQQyGN3G8Uc/DuSVMvPTjNbmlKs5E+wiau3qw8WalHz2NJZmfUv2B7ENFcDopXkDltzXeNj6zIwT90IB8m084E5iHyBZiNQdaq0hvgAJKoLAuSzKYEjx2qHqnjh1WGsUhjB2A==
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: cicd
    type: Opaque
