apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: myapp-triggertemplate
spec:
  params:
  - name: git_repo_url
    description: The git repository url
  - name: git_revision
    description: The git revision
  - name: git_repo_name
    description: The name of the deployment to be created / patch
  - name: ext_branch
  - name: environment
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: myapp-$(tt.params.git_repo_name)-$(tt.params.ext_branch)-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: myapp-ci-pipeline
      timeouts:
        pipeline: 1h0m0s
      params:
      - name: git_repo_name
        value: $(tt.params.git_repo_name)
      - name: git-url
        value: $(tt.params.git_repo_url)
      - name: git_revision
        value: $(tt.params.git_revision)
      - name: ext_branch
        value: $(tt.params.ext_branch)
      - name: environment
        value: "Default"
      workspaces:
      - name: source
        persistentVolumeClaim:
          claimName: myapp-source
      - name: secret
        secret:
          secretName: github-pat-secret
        
