apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-ci-pipeline
spec:
  params:
    - default: 'https://github.com/paichayon321/spring-web-quickstart.git'
      description: The git repository url
      name: git_repo_url
      type: string
    - default: main
      description: The git revision
      name: git_revision
      type: string
    - default: spring-web-quickstart
      description: The name of the deployment to be created / patched
      name: git_repo_name
      type: string
    - name: ext_branch
      type: string
      default: default
    - name: environment
      type: string
      default: default
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git_repo_url)
        - name: revision
          value: $(params.git_revision)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:697b1d12faa0c3ddde73706b304b3c267539bca689ae614815f2186d6befce0b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      workspaces:
        - name: output
          workspace: source
    - name: initial-info
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: git_repo_url
          value: $(params.git_repo_url)
        - name: git_revision
          value: $(params.git_revision)
        - name: git_repo_name
          value: $(params.git_repo_name)
        - name: ext_branch
          value: $(params.ext_branch)
        - name: environment
          value: $(params.environment)  
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: initial-info
      workspaces:
        - name: app-source
          workspace: source
    - name: unitest
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: MAVEN_IMAGE
          value: >-
            registry.redhat.io/ubi8/openjdk-17@sha256:0d12c4097e098b62f78a7a31c0d711d78e1e5a53f4c007b9a5fc6cc6ab4dc018
        - name: GOALS
          value:
            - test
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: ''
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - initial-info
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: source
    - name: sonarqube-scanner
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: SONAR_HOST_URL
          value: 'http://sonarqube-route-devopstools.apps.524vf.dynamic.opentlc.com/'
        - name: SONAR_PROJECT_KEY
          value: $(params.git_repo_name)-$(params.ext_branch)
        - name: PROJECT_VERSION
          value: $(tasks.initial-info.results.image_tag)
        - name: SOURCE_TO_SCAN
          value: .
        - name: SONAR_ORGANIZATION
          value: default
        - name: SONAR_SCANNER_IMAGE
          value: >-
            docker.io/sonarsource/sonar-scanner-cli:4.6@sha256:7a976330a8bad1beca6584c1c118e946e7a25fdc5b664d5c0a869a6577d81b4f
        - name: SONAR_LOGIN_KEY
          value: admin
        - name: SONAR_PASSWORD_KEY
          value: squ_8f7ec6ef6d6d83ba222a3cdfaf42ed5d31b790ed
        - name: SONAR_LOGIN_TOKEN
          value: squ_8f7ec6ef6d6d83ba222a3cdfaf42ed5d31b790ed
      runAfter:
        - unitest
      taskRef:
        kind: ClusterTask
        name: sonarqube-scanner-custom
      workspaces:
        - name: source
          workspace: source
        - name: sonar-settings
          workspace: source
        - name: sonar-credentials
          workspace: source
    - name: compile-mvn
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: MAVEN_IMAGE
          value: >-
            registry.redhat.io/ubi8/openjdk-17@sha256:0d12c4097e098b62f78a7a31c0d711d78e1e5a53f4c007b9a5fc6cc6ab4dc018
        - name: GOALS
          value:
            - '-Dmaven.test.skip'
            - '-Dquarkus.package.type=uber-jar'
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - unitest
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source
        - name: maven-settings
          workspace: source
    - name: buildimage
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: image_tag
          value: $(tasks.initial-info.results.image_tag)
        - name: app_name
          value: $(params.git_repo_name)
        - name: image_repo_url
          value: default-route-openshift-image-registry.apps.524vf.dynamic.opentlc.com/cicd
        - name: environment
          value: $(tasks.initial-info.results.environment)
        - name: IMAGE
          value: default
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:3c2ea396a114221575a4031d90d28c43563f7b96288374e0ba8b22de3ed97b5a
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./docker/Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - compile-mvn
        - sonarqube-scanner
      taskRef:
        kind: Task
        name: buildah-custom
      workspaces:
        - name: source
          workspace: source
        - name: dockerconfig
          workspace: source
    - name: update-manifest-dev
      params:
        - name: git_repo_name
          value: $(params.git_repo_name)
        - name: environment
          value: $(tasks.initial-info.results.environment)
        - name: image_tag
          value: $(tasks.initial-info.results.image_tag)
        - name: image_repo_url
          value: image-registry.openshift-image-registry.svc:5000/cicd
      runAfter:
        - buildimage
      taskRef:
        kind: Task
        name: update-manifest-task
      workspaces:
        - name: temp
          workspace: temp
        - name: secret
          workspace: secret
      when:
        - input: $(tasks.initial-info.results.environment)
          operator: in
          values:
            - "dev"
    - name: update-manifest-sit
      params:
        - name: git_repo_name
          value: $(params.git_repo_name)
        - name: environment
          value: $(tasks.initial-info.results.environment)
        - name: image_tag
          value: $(tasks.initial-info.results.image_tag)
        - name: image_repo_url
          value: image-registry.openshift-image-registry.svc:5000/cicd
      runAfter:
        - buildimage
      taskRef:
        kind: Task
        name: update-manifest-task
      workspaces:
        - name: temp
          workspace: temp
        - name: secret
          workspace: secret
      when:
        - input: $(tasks.initial-info.results.environment)
          operator: in
          values:
            - "tags"
  finally:
    - name: clean-taskrun
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"    
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - taskrun delete --keep 20 -f
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: clean-pipelinerun
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - pipelinerun delete --keep 5 -f
      taskRef:
        kind: ClusterTask
        name: tkn
  workspaces:
    - name: source
    - name: secret
    - name: temp

