apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-cd-pipeline
spec:
  params:
    - name: git_repo_name
      default: spring-web-quickstart
      description: The name of the deployment to be created
    - name: environment
      type: string
      default: uat
      description: Deploy environment name "uat" or "prod"
    - name: image_tag
      description: image version number in format x.y.z for example 1.0.0
    - name: image_repo_url
      default: image-registry.openshift-image-registry.svc:5000/cicd
      description: Image registry repository where image existing
  tasks:
# Update Manifest
    - name: update-manifest
      params:
        - name: image_tag
          value: $(params.image_tag)
        - name: git_repo_name
          value: $(params.git_repo_name)
        - name: environment
          value: $(params.environment)
        - name: image_repo_url
          value: $(params.image_repo_url)
      taskRef:
        kind: Task
        name: update-manifest-task
      workspaces:
        - name: temp
          workspace: temp
        - name: secret
          workspace: secret
  finally:
    - name: clean-taskrun
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - taskrun delete --keep 20 -f
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: clean-pipelinerun
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - pipelinerun delete --keep 5 -f
      taskRef:
        kind: ClusterTask
        name: tkn
  workspaces:
    - name: secret
      description: Select Secret > github-pat-secret
    - name: temp
      description: Use Empty Directory

