apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: myapp-ci-pipeline
spec:
  params:
    - default: 'https://github.com/paichayon321/spring-web-quickstart.git'
      description: The git repository url
      name: git_repo_url
      type: string
    - default: main
      description: The git revision
      name: git_revision
      type: string
    - default: spring-web-quickstart
      description: The name of the deployment to be created / patched
      name: git_repo_name
      type: string
    - name: ext_branch
      type: string
      default: default
    - name: environment
      type: string
      default: default
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git_repo_url)
        - name: revision
          value: $(params.git_revision)
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'false'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:697b1d12faa0c3ddde73706b304b3c267539bca689ae614815f2186d6befce0b
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      workspaces:
        - name: output
          workspace: source
    - name: get-branch-task
      when:
        - input: $(params.ext_branch)
          operator: notin
          values:
            - "refs-heads-main"
      params:
        - name: git_repo_url
          value: $(params.git_repo_url)
        - name: git_revision
          value: $(params.git_revision)
        - name: git_repo_name
          value: $(params.git_repo_name)
        - name: ext_branch
          value: $(params.ext_branch)
        - name: environment
          value: $(params.environment)  
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: get-branch-task
      workspaces:
        - name: app-source
          workspace: source
    - name: update-dev
      params:
        - name: message
          value: update dev environment with image tag $(tasks.get-branch-task.results.image_tag)
        - name: environment
          value: $(tasks.get-branch-task.results.environment)
        - name: image_tag
          value: $(tasks.get-branch-task.results.image_tag)
      runAfter:
        - get-branch-task
      taskRef:
        kind: ClusterTask
        name: echo
      when:
        - input: $(tasks.get-branch-task.results.environment)
          operator: in
          values:
            - "dev"
    - name: update-sit
      params:
        - name: message
          value: update sit environment with image tag $(tasks.get-branch-task.results.image_tag)
        - name: environment
          value: $(tasks.get-branch-task.results.environment)
        - name: image_tag
          value: $(tasks.get-branch-task.results.image_tag)
      runAfter:
        - get-branch-task
      taskRef:
        kind: ClusterTask
        name: echo
      when:
        - input: $(tasks.get-branch-task.results.environment)
          operator: in
          values:
            - "tags"
  finally:
    - name: clean-taskrun
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - taskrun delete --keep 20 -f
      taskRef:
        kind: ClusterTask
        name: tkn
    - name: clean-pipelinerun
      params:
        - name: TKN_IMAGE
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8@sha256:72394dfaed68c4b6b490c3c971fb1d9f0139f8656f6672b55b8e02ea98d1298d
        - name: SCRIPT
          value: tkn $@
        - name: ARGS
          value:
            - pipelinerun delete --keep 5 -f
      taskRef:
        kind: ClusterTask
        name: tkn
  workspaces:
    - name: source

