apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail-cd
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.0.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: mail
    tekton.dev/displayName: "send mail"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task sends a simple email to receivers via SMTP server
  params:
  - name: recipients
    type: string
    description: recipient email addresses
  - name: message
    type: string
    description: message
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - name: send
    image: docker.io/paichayon1/sendgmail-py:0.1
    script: |
      # echo "$(context.pipeline.name)"
      echo "message:tttt"
      echo $(params.message)
      echo $(context.pipeline.name)
      # Usage: python sendgmail.py sender_mail sender_password recipient_email subject body 
      #recipient_email="ptanvann@redhat.com"
      #subject="Pipeline Status:"
      # body="<b>Summary Pipeline Status</b><br>$(params.message)<br>"
      #body="test"
      #python sendgmail.py "$user" "$password" "$(params.recipients)" "$subject" "$body" 


