apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail-cd
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.0.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: mail
    tekton.dev/displayName: "send mail"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task sends a simple email to receivers via SMTP server
  params:
  - name: recipients
    type: string
    description: recipient email addresses
  - name: message
    type: string
    description: message
  - name: pipeline_name
    type: string
  - name: pipelinerun_name
    type: string  
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - name: send
    image: docker.io/paichayon1/sendgmail-py:0.1
    script: |
      #echo $(params.message)
      #echo $image_tag
      #echo $(params.pipeline_name)
      #echo $(params.pipelinerun_name)
      image_tag=$(echo $(params.message) | cut -d'|' -f1)
      environment=$(echo $(params.message) | cut -d'|' -f2)
      task_status=$(echo $(params.message) | cut -d'|' -f3- | sed 's/|/<br>/g')
      
      subject="Pipeline: $(params.pipeline_name) with run name: $(params.pipelinerun_name) for environment $environment status"
      body="<html><body><p><h1><b> Pipeline Status:</b></h1> <p> <b>PipelineRun name:</b> $(params.pipelinerun_name) <br> <b>Image:</b> $image_tag <br> <b>Environment:</b> $environment <br><h2><b> Task: </b></h2> $task_status </body></html>"
      
      echo "$subject"
      echo "$body"
      # Usage: python sendgmail.py sender_mail sender_password recipient_email subject body 
      python sendgmail.py "$user" "$password" "$(params.recipients)" "$subject" "$body" 


