apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: mail
    tekton.dev/displayName: "send mail"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task sends a simple email to receivers via SMTP server
  workspaces:
    - name: temp
      description: Workspace for temporary
  params:
  - name: subject
    type: string
    description: plain text email subject
  - name: body
    type: string
    description: plain text email body
  - name: sender
    type: string
    description: sender email address
  - name: recipients
    type: string
    description: recipient email addresses (space delimited list)
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - name: send
    image: docker.io/paichayon1/sendgmail-py:0.1
    script: |
      # Usage: python sendgmail.py sender_mail, sender_password, recipient_email, subject, body 
      sender_mail="$user"
      sender_password="$password"
      recipient_email="ptanvann@redhat.com "
      subject=" Test Subject"
      body=" Test Boby "
      python sendgmail.py sender_mail, sender_password, recipient_email, subject, body 


