apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail-cd
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.0.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: mail
    tekton.dev/displayName: "send mail"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task sends a simple email to receivers via SMTP server
  params:
  - name: recipients
    type: string
    description: recipient email addresses
  - name: message
    type: string
    description: message
  - name: pipeline_name
    type: string
  - name: pipelinerun_name
    type: string  
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - name: send
    image: docker.io/paichayon1/sendgmail-py:0.1
    script: |
      #echo $(params.message)
      #echo $image_tag
      #echo $(params.pipeline_name)
      #echo $(params.pipelinerun_name)
      image_tag=$(echo $(params.message) | cut -d'|' -f1)
      environment=$(echo $(params.message) | cut -d'|' -f2)
      task_status=$(echo $(params.message) | cut -d'|' -f3- | tr '|' "<br>")
      
      subject="Pipeline: $(params.pipeline_name) with run name: $(params.pipelinerun_name) for $environment status"
      body_temp="<p> Pipeline Status: <p> PipelineRun name: $(params.pipelinerun_name) <br> Image: $image_tag <br> Environment: $environment <br> Task: <br> $task_status"
      
      echo "$subject"
      echo "$body_temp"
      # Usage: python sendgmail.py sender_mail sender_password recipient_email subject body 
      #python sendgmail.py "$user" "$password" "$(params.recipients)" "$subject" "$body" 


