apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sendmail
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Messaging
    tekton.dev/tags: mail
    tekton.dev/displayName: "send mail"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    This task sends a simple email to receivers via SMTP server
  workspaces:
    - name: temp
      description: Workspace for temporary
  params:
#  - name: server
#    type: string
#    description: secret name for SMTP server information (url, port, password)
  - name: subject
    type: string
    description: plain text email subject
  - name: body
    type: string
    description: plain text email body
  - name: sender
    type: string
    description: sender email address
  - name: recipients
    type: string
    description: recipient email addresses (space delimited list)
  stepTemplate:
    envFrom:
      - secretRef:
          name: gmail-secret 
  steps:
  - name: send
    image: docker.io/library/python:3.8-alpine@sha256:e11bbd37d4371894e954421b85dbe8dd4eb7198d7cb4ed144ab529f19f57c3f1 #tag: 3.8-alpine
    script: |
      #!/usr/bin/env python3
     # import smtplib, ssl, os
     # from email.mime.text import MIMEText
     # port = "$port"
     # smtp_server = "$url"
     # sender_email = "$(params.sender)"
     # receiver_emails = "$(params.recipients)"
     # user = "$user"
     # password = "$password"
     # tls = 'True'

   #   message = f"""\
   #   Subject: $(params.subject)
   #   To: {receiver_emails}
   #   From: {sender_email}
   #   TLS: {tls}
      import smtplib
      from email.mime.text import MIMEText
      sender_email = "$user"
      sender_password = "$password"
      recipient_email = "recipient@gmail.com"
      subject = "Hello from Python"
      body = """
      <html>
        <body>
          <p>This is an <b>HTML</b> email sent from Python using the Gmail SMTP server.</p>
        </body>
      </html>
      """
#      html_message = MIMEText(body, 'html')
#      html_message['Subject'] = subject
#      html_message['From'] = sender_email
#      html_message['To'] = recipient_email
#      with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
#         server.login(sender_email, sender_password)
#         server.sendmail(sender_email, recipient_email, html_message.as_string())
#     
     # def send_email("$(params.subject)", "$(params.body)", sender_email, receiver_emails, password):

     # $(params.body)"""
     # print(message)
     # if tls == 'True':
     #     context = ssl.create_default_context()
     #     server = smtplib.SMTP_SSL(smtp_server, port, context=context)
     # else:
     #     server = smtplib.SMTP(smtp_server, port)
     # if password != '':
     #     server.login(user, password)
     # for receiver in [item for item in receiver_emails.split(' ') if item]:
     #     server.sendmail(sender_email, receiver, message.encode('utf-8'))
     #     # server.sendmail(sender_email, receiver, message.as_string())
     # server.quit()
