apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarqube-secret
  namespace: cicd
spec:
  encryptedData:
    SONAR_HOST_URL: AgCePwuRxiY7gKQ/tTRJGnbmFIhHGdUWIT4Vl1hDPAgut5RXgzSzUn4ZrA4XPfkWfCenMRJoqzn8cBb/chYuyRGmx+W/74upgtqY6J5vvrAX3goEP9djIHgYyHvUJr4Nms4Q8riAOV+GUgHfBOLfkQGuu7+B4i+orarBvC4N7q7xR5zgwumPhwJ/aDRb2sAcxv7oK16B4PWdcoJ9st2CTKvvJ9JFyJ2Fs7DJBIQVF1BKsG/TR84cwFZghKIPI1s8hK98ce7YR7sTqug+jHc3akuVExxuhR39RAsHDPONVUERV0oLym/H/Pg2xUZbIg3yUqeCAopC/8VvlX9wHf/vGv/yCjel/iu1dFy0hc10fCpHt8t/yM1OhLa12khs7hkJSCR1ysApsX9CR+HfFuG+39Otr3XeTP0koVrzNagmKFeEyOZ41+IQw9TzmpaMRFc2LABq90GK4Li7YJ7C+8J6EfD8Ck/RQqOsOE7SXdeKnRB2HUiGocTnmfQin6EiptmbhkHAt6BOkKLkZgY1HiXt4LPDb3lcW0qJKK5aqFvbpNhXpsSexbM2zkSAnUPYrned4F870NoUL4Pdm087xS6AzmQ0qIz8jEbZyAm3egHJcup2P2cDCgsnNuvlTebAjztxyCM4tIXvBavpC7nZPSo0Wv49z5YnpDYAv22jCzDBWmny+qT8Tl0S0B8j8ft2ui0dLuRFFl9XbkHo6LExOZ1tuAisMQed4BSPdgEdzOcXeR0NOimPsYzs3KHXA68FtOJWCThpjLoiH1ftEBLV5LB7s6dAquw=
    SONAR_LOGIN_TOKEN: AgCqkCkvtJ2TClabaOlzw5lrLtDKVM5ODeJMdlORMr2ArJ02zC89SoHt4j8DUf3s5h+KlcvFvndzSXbaRdaap92zW11SV+KtGBxxZdlZPIbNZT1uJQ4ktSHPX51Sb9+PEX9W3QjOn6HwFhi5R2hQMhTgZoeyUCZ4UWTWLPi1TzKnvpu5/FyxmLaLMw8mjKf/R6f0mjp3ClFt/SzPdHz4oNBj2burhE2PGynm+vpriVuMfz7SWkdnupM3erSwJvvgcZIpcNl68XcAdx4V2D9bP/FjXBMHesvPH4eeYwDb9GWz4RDJ3+ZKw/yUfjLgSLR0lSAgftctGw3tOhj3/rzRLnKsgcRmITLGzuhNPkd0coZdD1R4GFzGQosRnovWjMGwpZr5ysa9ZIha2+KTHy2sRwq6imAeM9NPMxdhSB4l7fb7CmK9eZ4kl5vpV7ysYpfo5tovbPdvTaA8RuS9tv1SRbQohNiGwD4TEtiVG1nKXegclNMgOYjRuEOZhnskOFGQokzoxt2cStsym3RI2SPfObWk6mUSFsV3X5W597bwFo6Z/127dVsQHOe3KC1KeQZKOgy3bQiaJnD6Qos7WpGRDPc6mGn4WUmmmOgeVIXxv/NEm+J38wNLSWKjw6P9qHfE5uY9NcuSkdgC28iKlauAU4fKMHPmcpcRjqcY2VCFkEWHBoLVk2PMBOkUhHhv3t8xpdHRyLZyMNprQoiftKDdWAIVMCDA4ZCevYHBIIS20ykIRTYtRqYRGEhk8aQcDA==
  template:
    metadata:
      creationTimestamp: null
      name: sonarqube-secret
      namespace: cicd
    type: Opaque
