apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: approval
spec:
  steps:
  - image: registry.redhat.io/ubi7/ubi-minimal
    name: wait-approve
    script: |
      # loop until approval=true
      echo "Wait for Approval=true"
      sleep infinity
      export approval=default

      # Your main loop
      while [ "$approval" != true ]; do
          # Your main script logic goes here
          echo "Waiting for approval..."
          exit 0
      done
      
      echo "Approvel and Exit 0"
      