apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: approval
spec:
  steps:
  - image: registry.redhat.io/ubi7/ubi-minimal
    name: wait-approve
    script: |
      # loop until approval=true
      echo "Wait for Approval=true"
      echo "default" > workspace/source/approval.txt

      # Your main loop
      while [ "$approval" != "true" ]; do
          # Your main script logic goes here
          approval=$(cat workspace/source/approval.txt"
          echo $approval
          echo "Waiting for approval..."

          sleep 3

      done
      
      echo "Approvel and Exit 0"
      exit 0
  workspaces:
    - name: source