apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: approval
spec:
  steps:
  - image: registry.redhat.io/ubi7/ubi-minimal
    name: wait-approve
    env:
      - name: approval
        value: default
    script: |
      # loop until approval=true
      echo "Wait for Approval=true"
      export approval=default

      # Your main loop
      while [ "$approval" != true ]; do
          # Your main script logic goes here
          echo $approval
          echo "Waiting for approval..."

          sleep 3

      done
      
      echo "Approvel and Exit 0"
      exit 0
      