apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-approve
  namespace: cicd
spec:
  tasks:
    - name: first-step
      params:
        - name: cmd
          value: echo "First"
      taskRef:
        kind: ClusterTask
        name: bash
      workspaces:
        - name: source
          workspace: source
    - name: custom-approval-pre-oc
      params:
        - name: recipients
          value: ptanvann@redhat.com
        - name: pipeline_name
          value: $(context.pipeline.name) 
        - name: pipelinerun_name
          value: $(context.pipelineRun.name)     
      runAfter:
        - first-step
      taskRef:
        kind: Task
        name: custom-approval-pre-oc
    - name: wait-for-approve
      params:
        - name: recipients
          value: ptanvann@redhat.com
        - name: pipeline_name
          value: $(context.pipeline.name) 
        - name: pipelinerun_name
          value: $(context.pipelineRun.name)     
      runAfter:
        - first-step
      taskRef:
        kind: Task
        name: custom-approval
    - name: custom-approval-post-oc
      params:
        - name: recipients
          value: ptanvann@redhat.com
        - name: pipeline_name
          value: $(context.pipeline.name) 
        - name: pipelinerun_name
          value: $(context.pipelineRun.name)     
      runAfter:
        - wait-for-approve
        - custom-approval-pre-oc
      taskRef:
        kind: Task
        name: custom-approval-post-oc
    - name: after-approve
      params:
        - name: cmd
          value: echo "Run After approve=true"
      runAfter:
        - wait-for-approve
      taskRef:
        kind: ClusterTask
        name: bash
      workspaces:
        - name: source
          workspace: source
  workspaces:
    - name: source