apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "update-manifest-task"
spec:
  params:
  - name: git_repo_name
    type: string
    default: ""
  description: >-
    update-manifest-task
  workspaces:
    - name: source
      description: Workspace containing the code
    - name: secret
      description: GITHUB PAT secret - user and token 
  steps:
    - env:
        - name: git_repo_name
          value: $(params.git_repo_name)     
        - name: GIT_CREDS_USR
        - name: GIT_CREDS_PSW
      name: clone-platform-repo
      image: docker.io/paichayon1/multitools:ubi7
      workingDir: $(workspaces.source.path)
      script: |
        #git clone https://github.com/paichayon321/tekton-pipeline.git
        echo $(workspaces.secret.path)
        GIT_CREDS_USR=$(cat $(workspaces.secret.path)/user)
        echo $GIT_CREDS_USR
        GIT_CREDS_PSW=$(cat $(workspaces.secret.path)/token)
        echo $GIT_CREDS_PWD
        git clone https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/paichayon321/tekton-pipeline.git
        cd tekton-pipeline
        git checkout origin/main
        ls -la
        
        #ls -la tekton-pipeline/app/myapp/env/dev
        #yq -i ".spec.template.spec.containers[0].image = xxxx" tekton-pipeline/app/myapp/env/dev/deployment.yaml
        #cat tekton-pipeline/app/myapp/env/dev/deployment.yaml
        #yq -i '.spec.template.spec.containers[0].image = "'''+image_name_tag+'''"' prescreening/backend/openshift/environment/'''+environment+'''/deployment.yaml
        #git add prescreening/backend/openshift/environment/'''+environment+'''/deployment.yaml
        #git commit -m 'update image '''+image_name_tag+''' on '''+environment+''' environment'
        #git push https://${GIT_CREDS_USR}:${GIT_CREDS_PSW}@192.168.77.24/devops/platform.git HEAD:main.   

        sleep infinity
