apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "update-manifest-task"
spec:
  params:
  - name: git_repo_name
  - name: environment
  - name: image_tag
  - name: image_repo_url
  description: >-
    update-manifest-task
  workspaces:
    - name: source
      description: Workspace containing the code
    - name: secret
      description: GITHUB PAT secret - user and token 
  steps:
    - env:
        - name: git_repo_name
          value: $(params.git_repo_name) 
        - name: environment
          value: $(params.environment) 
        - name: image_tag
          value: $(params.image_tag)               
        - name: GIT_CREDS_USR
        - name: GIT_CREDS_PSW
        - name: deploy_env
      name: clone-platform-repo
      image: docker.io/paichayon1/multitools:ubi7
      workingDir: $(workspaces.source.path)
      script: |
        echo "####################"
        echo $(params.environment)
        echo "####################"

        if [[ $(params.environment) == dev ]]; then
            deploy_env=dev
        elif [[ $(params.environment) == tags ]]; then
            deploy_env=sit
        else
            exit 1
        fi  


        GIT_CREDS_USR=$(cat $(workspaces.secret.path)/user)
        GIT_CREDS_PSW=$(cat $(workspaces.secret.path)/token)
        git clone https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/paichayon321/tekton-pipeline.git
        cd tekton-pipeline
        git checkout origin/main
        git config --global user.name "tekton_pipeline"
        git config --global user.email "tektonPipeline@domain.local"
        yq -i '.spec.template.spec.containers[0].image = "$(params.image_repo_url)/$(params.git_repo_name):$(params.image_tag)"' /workspace/source/tekton-pipeline/app/myapp/env/$deploy_env/deployment.yaml
        git add /workspace/source/tekton-pipeline/app/myapp/env/$deploy_env/deployment.yaml
        git commit -m 'update image $(params.git_repo_name):$(params.image_tag) on "$deploy_env"'
        git push https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/paichayon321/tekton-pipeline.git HEAD:main   

