apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "update-manifest-task"
spec:
  params:
  - name: git_repo_name
    type: string
    default: ""
  description: >-
    update-manifest-task
  workspaces:
    - description: Workspace containing the code
      name: source
  steps:
    - env:
        - name: git_repo_name
          value: $(params.git_repo_name)       
      name: debug-git-task
      image: cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
      workingDir: $(workspaces.source.path)
      script: |
        pwd
        ls -la
        git --help
        sleep infinity
