apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.1"
    tekton.dev/displayName: "update-manifest-task"
spec:
  params:
  - name: git_repo_name
    type: string
    default: ""
  description: >-
    update-manifest-task
  workspaces:
    - description: Workspace containing the code
      name: source
  steps:
    - env:
        - name: git_repo_name
          value: $(params.git_repo_name)       
      name: clone-repo
      image: cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
      workingDir: $(workspaces.source.path)
      script: |
        pwd
        ls -la
        git --help
        git clone https://github.com/paichayon321/tekton-pipeline.git
        #git clone https://${GIT_CREDS_USR}:${GIT_CREDS_PSW}@192.168.77.24/devops/platform.git
        #cd platform
        #git checkout origin/main
        #yq -i '.spec.template.spec.containers[0].image = "'''+image_name_tag+'''"' prescreening/backend/openshift/environment/'''+environment+'''/deployment.yaml
        #git add prescreening/backend/openshift/environment/'''+environment+'''/deployment.yaml
        #git commit -m 'update image '''+image_name_tag+''' on '''+environment+''' environment'
        #git push https://${GIT_CREDS_USR}:${GIT_CREDS_PSW}@192.168.77.24/devops/platform.git HEAD:main.   

    - name: update-manifest
      image: stedolan/jq
      workingDir: $(workspaces.source.path)      
      script: |
        pwd
        ls -la
    - name: sleep
      image: registry.redhat.io/ubi7/ubi-minimal
      workingDir: $(workspaces.source.path)  
      script: |
        sleep infinity