kind: Service
apiVersion: v1
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  ports:
    - name: port-1
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: myapp

