apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: sonarqube
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sonarqube-route
spec:
  to:
    kind: Service
    name: sonarqube
    weight: 100
  port:
    targetPort: 9000